name: Deploy shirokuma docs via GitHub Pages

on:
  push:
    branches:
      - main

env:
  cache_path: |
    ~/.npm

jobs:
  deploy-js-docs:
    name: Deploy shirokuma API documentation

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        # This action also handles dependency caching for us
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc

      - name: Restore from npm cache
        uses: actions/cache@v2
        with:
          path: ${{ env.cache_path }}
          # Note that this caching action does NOT cache node dependencies.
          # This is done by "actions/setup-node" instead. Here we're caching
          # npm artifacts.
          key: ${{ runner.os }}-test-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Build documentation page
        run: npm run docs

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

